# Generated by Django 2.1.4 on 2018-12-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('job_title', models.TextField(max_length=100)),
                ('date_started', models.DateTimeField()),
                ('description', models.TextField(default='enter description here', max_length=300)),
                ('photo', models.ImageField(default='default.jpg', upload_to='media')),
            ],
        ),
    ]
